### ISSUE TITLE
Create package for gemma

### ISSUE THREAD

**Issue by vinriviere** [vinriviere/cross-mint-ubuntu#1]
The gemma library is mature enough to create a Debian package.
It is now in a separate repository:
https://github.com/freemint/gemma

**Comment by vinriviere** [comment]
@mikrosk, @th-otto: Can you please point me to the start of our discussion about this topic? I can't find it again inside GitHub's mess.

**Comment by th-otto** [comment]
I think you mean https://github.com/freemint/gemlib/issues/6

If not, what do you need to know?

**Comment by vinriviere** [comment]
I mean the thread where I was asked to build an Ubuntu package. I can't find it. Maybe it was a discussion directly on a commit, not on an issue?

**Comment by mikrosk** [comment]
Maybe this? https://mikro.naprvyraz.sk/mint/freemint-list/Week-of-Mon-20170424/000919.html

**Comment by vinriviere** [comment]
No, I mean the thread where we spoke yesterday. I have dumbly deleted the notification emails. Really, GitHub is a real mess.

**Comment by mikrosk** [comment]
Found it: https://github.com/freemint/freemint/commit/9d82cbac690c82bd116fc37eb8c70506503f27bc#commitcomment-29708920

**Comment by vinriviere** [comment]
Ah, many thanks! It seems that GitHub is unable to find such comment on commit from its search box. Or I did it wrong.

**Comment by vinriviere** [comment]
gemma: done (latest version).

Please do:
```
sudo apt update
sudo apt install gemma-m68k-atari-mint
```
And tell me if that's fine for you.

**Comment by mikrosk** [comment]
@th-otto as soon as you revert https://github.com/freemint/freemint/commit/9d82cbac690c82bd116fc37eb8c70506503f27bc, https://github.com/freemint/freemint/blob/master/.travis.yml needs this into 'packages' section.

**Comment by th-otto** [comment]
Done. Note that if make complains about not knowing how to create slb/gemma.h when building in your local clone, you just have to delete your .deps directory(s).

**Comment by mikrosk** [comment]
Thank you both guys! It's not the most important victory in the FreeMiNT project but it's a nice feeling to have this sorted.

**Comment by vinriviere** [comment]
Good! That's one good thing.
Now I'm looking for mkfatfs for ColdFire. Will it be available somewhere?

**Comment by mikrosk** [comment]
> Now I'm looking for mkfatfs for ColdFire. Will it be available somewhere?

You  mean except the freemint snapshots? (mint/1-xx-yyy/sysroot/bin/mkfatfs.ttp)

**Comment by vinriviere** [comment]
No, I mean in the absolute. And you gave me the answer 🙂
As libgemma.a is now compiled for ColdFire, it should the first time that mkfatfs.ttp is available 100% ColdFire. I will try it on the FireBee.
I notice there are also many other programs in `sysroot/bin`, each ones should be checked to be 100% ColdFire native. I believe we already cared about most libraries, if not all, so most programs should be OK.

**Comment by mikrosk** [comment]
If there is even one program not built with -mcpu=5475 I'd definitely consider it as a bug. That's the whole point of having the CF-specific archive! I think it was @th-otto who'd fixed the Makefiles and CPU= propagation.

**Comment by th-otto** [comment]
> it should the first time that mkfatfs.ttp is available 100% ColdFire.

mkfatfs was already available for quite some time, only the GUI for it (gemkfatfs) is new ;)

> I will try it on the FireBee.

That would be nice. Has already been done some time ago with my manually compiled version (see http://atari-forum.com/viewtopic.php?f=14&t=32433), but definitely should be done now again for the official version.

**Comment by vinriviere** [comment]
Oh, good. I wasn't aware of that.
I have just opened an issue to check that official FreeMiNT build for ColdFire is 100% ColdFire:
https://github.com/freemint/freemint/issues/91
